format = '''
[â”Œâ”€>](bold green) $git_branch$git_status$python$conda\[$username$hostname\]
[â”œâ”€>](bold green) $directory
[â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green) '''

[username]
# style_user = 'red bold'
# style_root = 'black bold'
format = '$user'
disabled = false
show_always = true


[hostname]
ssh_only = true
format = '@[$hostname](bold red)[$ssh_symbol](bold blue)  '
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false
truncation_symbol = 'â€¦/'

[python]
format = '[(\(py-venv${symbol}: $virtualenv ${pyenv_prefix}\) )]($style)'
symbol = 'ğŸ'

[conda]
format = '[(\(conda${symbol}: $environment\) )]($style)'
symbol = 'ğŸ'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
