format = '''
[‚îå‚îÄ>](bold green) $git_branch$python\[$username$hostname\]
[‚îú‚îÄ>](bold green) $directory
[‚îî‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ>](bold green) '''


[username]
# style_user = 'red bold'
# style_root = 'black bold'
format = '$user'
disabled = false
show_always = true


[hostname]
ssh_only = true
format = '@[$hostname](bold red)[$ssh_symbol](bold blue)  '
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false
truncation_symbol = '‚Ä¶/'

[python]
format='[(\($virtualenv ${symbol}${pyenv_prefix}\) )]($style)'
symbol='üêç'

[git_branch]
format='[$symbol$branch(:$remote_branch)]($style) '
